### PR TITLE
Quickfix for a crash if user count is too low

### PR DESCRIPTION
**Pull request by izmalk**
Fixing a crash due to 0 members (and 0 candidates) for user_group documentation if `user count` setting is too low.

### CODE REVIEW

**Comment by izmalk** [comment]
This PR is outdated since the repository updated a lot and I have tested an outdated version.

**Comment by izmalk** [comment]
I have tested it and it seems like this fix is still needed to operate with low numbers of users.

**Review by james-whiteside — CHANGES_REQUESTED** [review]
Please change `candidate_owner_uuids.__len__()` to `len(candidate_owner_uuids)` to better conform with style.

**Comment by izmalk** [comment]
> Please change `candidate_owner_uuids.__len__()` to `len(candidate_owner_uuids)` to better conform with style.

Fixed in https://github.com/james-whiteside/typedb_iam/pull/1#:~:text=conform%20with%20style.-,Fix%20after%20review,-Verified

**Review by james-whiteside — APPROVED** [review]

**Pull request merged**
